<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite start="1684757780036" stop="1684757851837" version="1.5.4" xmlns:ns2="urn:model.allure.qatools.yandex.ru">
    <name>ULP_BFF_Test_Suite : ULP_BFF</name>
    <title>ULP_BFF_Test_Suite : ULP_BFF</title>
    <test-cases>
        <test-case start="1684757780147" stop="1684757783524" status="passed">
            <name>API_01_VerifyUserIsAbleToGenerateDigiUrl</name>
            <title>Verify that user is able to generate digiurl</title>
            <description type="text">Verify that user is able to generate digiurl </description>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="ULP_BFF_Test_Suite"/>
                <label name="testGroup" value="ULP_BFF"/>
                <label name="testClass" value="com.api.script.DigilockerEwalletTest"/>
                <label name="testMethod" value="API_01_VerifyUserIsAbleToGenerateDigiUrl"/>
                <label name="host" value="DESKTOP-UJIBV1G"/>
                <label name="thread" value="8684@DESKTOP-UJIBV1G.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1684757783537" stop="1684757850252" status="broken">
            <name>API_02_VerifyUserIsAbleToGenerateAuthCode</name>
            <title>Verify that user is able to generate auth code</title>
            <description type="text">Verify that user is able to generate auth code</description>
            <failure>
                <message>NoSuchWindowException: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=113.0.5672.127)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-UJIBV1G', ip: '192.168.1.100', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 113.0.5672.127, chrome: {chromedriverVersion: 113.0.5672.63 (0e1a4471d5ae..., userDataDir: C:\Users\SNEHAL\AppData\Loc...}, goog:chromeOptions: {debuggerAddress: localhost:57943}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 558cd07dff60e38b80de2a2e04c4484e</message>
                <stack-trace>org.openqa.selenium.NoSuchWindowException: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=113.0.5672.127)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-UJIBV1G', ip: '192.168.1.100', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 113.0.5672.127, chrome: {chromedriverVersion: 113.0.5672.63 (0e1a4471d5ae..., userDataDir: C:\Users\SNEHAL\AppData\Loc...}, goog:chromeOptions: {debuggerAddress: localhost:57943}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 558cd07dff60e38b80de2a2e04c4484e&#13;
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)&#13;
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)&#13;
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)&#13;
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)&#13;
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)&#13;
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)&#13;
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)&#13;
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)&#13;
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)&#13;
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)&#13;
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:609)&#13;
	at org.openqa.selenium.remote.RemoteWebDriver.getCurrentUrl(RemoteWebDriver.java:287)&#13;
	at com.pageFactory.DigiLockerLoginPage.getAuthCode(DigiLockerLoginPage.java:64)&#13;
	at com.api.view.APIview.EnterDetailsOnDigilockerLoginPageUsingMobile(APIview.java:138)&#13;
	at com.api.script.DigilockerEwalletTest.API_02_VerifyUserIsAbleToGenerateAuthCode(DigilockerEwalletTest.java:57)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)&#13;
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)&#13;
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)&#13;
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)&#13;
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)&#13;
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)&#13;
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)&#13;
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
	at org.testng.TestRunner.privateRun(TestRunner.java:794)&#13;
	at org.testng.TestRunner.run(TestRunner.java:596)&#13;
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)&#13;
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)&#13;
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)&#13;
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)&#13;
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)&#13;
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)&#13;
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)&#13;
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)&#13;
	at org.testng.TestNG.runSuites(TestNG.java:1063)&#13;
	at org.testng.TestNG.run(TestNG.java:1031)&#13;
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)&#13;
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)&#13;
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)&#13;
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="ULP_BFF_Test_Suite"/>
                <label name="testGroup" value="ULP_BFF"/>
                <label name="testClass" value="com.api.script.DigilockerEwalletTest"/>
                <label name="testMethod" value="API_02_VerifyUserIsAbleToGenerateAuthCode"/>
                <label name="host" value="DESKTOP-UJIBV1G"/>
                <label name="thread" value="8684@DESKTOP-UJIBV1G.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1684757850268" stop="1684757850955" status="broken">
            <name>API_03_VerifyUserIsAbleToGenerateToken</name>
            <title>Verify user is able to generate token</title>
            <description type="text">Verify user is able to generate token</description>
            <failure>
                <message>NullPointerException: Cannot invoke "com.api.pojoResponse.Digi.getAccess_token()" because the return value of "com.api.pojoResponse.DigiLockerTokenEwalletResponse.getDigi()" is null</message>
                <stack-trace>java.lang.NullPointerException: Cannot invoke "com.api.pojoResponse.Digi.getAccess_token()" because the return value of "com.api.pojoResponse.DigiLockerTokenEwalletResponse.getDigi()" is null&#13;
	at com.api.view.APIview.getAccessToken(APIview.java:179)&#13;
	at com.api.script.DigilockerEwalletTest.API_03_VerifyUserIsAbleToGenerateToken(DigilockerEwalletTest.java:76)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)&#13;
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)&#13;
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)&#13;
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)&#13;
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)&#13;
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)&#13;
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)&#13;
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
	at org.testng.TestRunner.privateRun(TestRunner.java:794)&#13;
	at org.testng.TestRunner.run(TestRunner.java:596)&#13;
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)&#13;
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)&#13;
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)&#13;
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)&#13;
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)&#13;
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)&#13;
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)&#13;
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)&#13;
	at org.testng.TestNG.runSuites(TestNG.java:1063)&#13;
	at org.testng.TestNG.run(TestNG.java:1031)&#13;
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)&#13;
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)&#13;
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)&#13;
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="ULP_BFF_Test_Suite"/>
                <label name="testGroup" value="ULP_BFF"/>
                <label name="testClass" value="com.api.script.DigilockerEwalletTest"/>
                <label name="testMethod" value="API_03_VerifyUserIsAbleToGenerateToken"/>
                <label name="host" value="DESKTOP-UJIBV1G"/>
                <label name="thread" value="8684@DESKTOP-UJIBV1G.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1684757850973" stop="1684757851765" status="broken">
            <name>API_01_VerifyUserIsAbleToSearchStudent</name>
            <title>Verify user is able to search student</title>
            <description type="text">Verify user is able to search student</description>
            <failure>
                <message>NullPointerException: Cannot invoke "java.util.List.get(int)" because the return value of "com.api.pojoResponse.BffCredentialsSearchStudentsresponse.getResult()" is null</message>
                <stack-trace>java.lang.NullPointerException: Cannot invoke "java.util.List.get(int)" because the return value of "com.api.pojoResponse.BffCredentialsSearchStudentsresponse.getResult()" is null&#13;
	at com.api.view.APIview.getCredentialID(APIview.java:433)&#13;
	at com.api.script.DigilockerBFFCredentialsTest.API_01_VerifyUserIsAbleToSearchStudent(DigilockerBFFCredentialsTest.java:57)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)&#13;
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)&#13;
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)&#13;
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)&#13;
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)&#13;
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)&#13;
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)&#13;
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
	at org.testng.TestRunner.privateRun(TestRunner.java:794)&#13;
	at org.testng.TestRunner.run(TestRunner.java:596)&#13;
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)&#13;
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)&#13;
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)&#13;
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)&#13;
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)&#13;
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)&#13;
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)&#13;
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)&#13;
	at org.testng.TestNG.runSuites(TestNG.java:1063)&#13;
	at org.testng.TestNG.run(TestNG.java:1031)&#13;
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)&#13;
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)&#13;
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)&#13;
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="ULP_BFF_Test_Suite"/>
                <label name="testGroup" value="ULP_BFF"/>
                <label name="testClass" value="com.api.script.DigilockerBFFCredentialsTest"/>
                <label name="testMethod" value="API_01_VerifyUserIsAbleToSearchStudent"/>
                <label name="host" value="DESKTOP-UJIBV1G"/>
                <label name="thread" value="8684@DESKTOP-UJIBV1G.main(1)"/>
            </labels>
        </test-case>
    </test-cases>
    <labels>
        <label name="framework" value="TestNG"/>
        <label name="language" value="JAVA"/>
    </labels>
</ns2:test-suite>
