<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite start="1683104047033" stop="1683104051168" version="1.5.4" xmlns:ns2="urn:model.allure.qatools.yandex.ru">
    <name>Default suite : Default test</name>
    <title>Default suite : Default test</title>
    <test-cases>
        <test-case start="1683104047153" stop="1683104050952" status="broken">
            <name>VerifyUserIsAbleToGenerateDigiUrl</name>
            <title>Verify that user is able to generate digi auth url</title>
            <description type="text">Verify that user is able to generate digi auth url </description>
            <failure>
                <message>NullPointerException: Cannot invoke "com.generic.WrapperFunctions.logReporter(String, String, boolean)" because the return value of "com.generic.Pojo.getObjWrapperFunctions()" is null</message>
                <stack-trace>java.lang.NullPointerException: Cannot invoke "com.generic.WrapperFunctions.logReporter(String, String, boolean)" because the return value of "com.generic.Pojo.getObjWrapperFunctions()" is null&#13;
	at com.api.view.APIview.setCreateResposeAPI(APIview.java:45)&#13;
	at com.api.script.DigilockerEwalletTest.VerifyUserIsAbleToGenerateDigiUrl(DigilockerEwalletTest.java:44)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)&#13;
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)&#13;
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)&#13;
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)&#13;
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)&#13;
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)&#13;
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)&#13;
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
	at org.testng.TestRunner.privateRun(TestRunner.java:794)&#13;
	at org.testng.TestRunner.run(TestRunner.java:596)&#13;
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)&#13;
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)&#13;
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)&#13;
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)&#13;
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)&#13;
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)&#13;
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)&#13;
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)&#13;
	at org.testng.TestNG.runSuites(TestNG.java:1063)&#13;
	at org.testng.TestNG.run(TestNG.java:1031)&#13;
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)&#13;
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)&#13;
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)&#13;
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="Default suite"/>
                <label name="testGroup" value="Default test"/>
                <label name="testClass" value="com.api.script.DigilockerEwalletTest"/>
                <label name="testMethod" value="VerifyUserIsAbleToGenerateDigiUrl"/>
                <label name="host" value="DESKTOP-UJIBV1G"/>
                <label name="thread" value="1476@DESKTOP-UJIBV1G.main(1)"/>
            </labels>
        </test-case>
    </test-cases>
    <labels>
        <label name="framework" value="TestNG"/>
        <label name="language" value="JAVA"/>
    </labels>
</ns2:test-suite>
